import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/features/common/components/atoms/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased bg-white`} suppressHydrationWarning>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
